# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('business_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique_for_date='created_date')),
                ('shop_number', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=40)),
                ('town', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('pin_code', models.IntegerField()),
            ],
            bases=('people.person',),
        ),
    ]
