# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('people.person',),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
