# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20160407_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'My Entry',
                'verbose_name_plural': 'My Entries',
            },
        ),
    ]
