# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_myentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyEntry',
        ),
        migrations.AddField(
            model_name='contractor',
            name='first_tie_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
