# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20160408_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='baseentity_ptr',
            field=models.OneToOneField(auto_created=True, default=34, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.BaseEntity'),
            preserve_default=False,
        ),
    ]
