# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20160409_2013'),
        ('services', '0005_auto_20160409_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='associate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='associate_services', to='people.Contractor'),
            preserve_default=False,
        ),
    ]
