# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 17:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20160409_2013'),
        ('workflow', '0004_auto_20160411_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.BaseEntity')),
                ('title', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Mixing', 'Mixing'), ('Titles', 'Titles'), ('Completed', 'Completed')], max_length=30)),
                ('priority', models.CharField(choices=[('Lowes', 'Lowest'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Highest', 'Highest'), ('Critical', 'Critical')], max_length=30)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='people.Customer')),
            ],
            bases=('people.baseentity',),
        ),
        migrations.AddField(
            model_name='event',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.Customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='total',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_served', to='people.Contractor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_assigned', to='people.Employee'),
        ),
    ]
