# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 17:42
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0008_auto_20160409_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.BaseEntity')),
                ('name', models.CharField(max_length=40)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('consumed_units', models.IntegerField(blank=True, null=True)),
                ('minimum_units_to_be_maintained', models.IntegerField(blank=True, null=True)),
            ],
            bases=('people.baseentity',),
        ),
    ]
