# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:50
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('consumed_units', models.IntegerField(blank=True, null=True)),
                ('minimum_units_to_be_maintained', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
